Name:           skj-logos
Version:        44.0
Release:        3%{?dist}
Summary:        SKJ OS EZ logos and icons
License:        CC-BY-SA-4.0 AND OFL-1.1
BuildArch:      noarch

# Everything is taken from _sourcedir: assets/ (generated by
# artwork/generate.py) and src/ (hand-written config files).

Provides:       system-logos = %{version}-%{release}
Conflicts:      fedora-logos
Conflicts:      generic-logos

%description
Logos and icons for SKJ OS EZ ISO Edition. They are installed at the paths
where Fedora's logos normally live, so installer, login screen and desktop
pick up the SKJ branding without further changes.

%package -n skj-backgrounds-kde
Summary:        SKJ OS EZ default wallpaper for KDE Plasma
License:        CC-BY-SA-4.0
Provides:       system-backgrounds-kde = %{version}-%{release}
Conflicts:      desktop-backgrounds-kde

%description -n skj-backgrounds-kde
Default SKJ OS EZ wallpaper for the KDE Plasma desktop, lock screen and
login screen.

%package -n plymouth-theme-skj
Summary:        SKJ OS EZ boot splash
License:        CC-BY-SA-4.0
Requires:       plymouth-plugin-two-step
Requires:       plymouth-theme-spinner
Requires(post): plymouth-scripts

%description -n plymouth-theme-skj
Plymouth boot splash showing the SKJ OS EZ logo with a spinner.

%package -n skj-fastfetch-config
Summary:        SKJ OS EZ system-wide fastfetch configuration
License:        MIT
Recommends:     fastfetch

%description -n skj-fastfetch-config
System-wide fastfetch configuration with the SKJ OS EZ logo.

%prep

%build

%install
A=%{_sourcedir}/assets
S=%{_sourcedir}/src

# --- skj-logos --------------------------------------------------------------
install -Dpm 0644 $A/svg/skj-logo-mark.svg        %{buildroot}%{_datadir}/skj-logos/skj-logo-mark.svg
install -Dpm 0644 $A/svg/skj-logo-mark-white.svg  %{buildroot}%{_datadir}/skj-logos/skj-logo-mark-white.svg
install -Dpm 0644 $A/svg/skj-wordmark-darkbg.svg  %{buildroot}%{_datadir}/skj-logos/skj-wordmark-darkbg.svg
install -Dpm 0644 $A/svg/skj-wordmark-lightbg.svg %{buildroot}%{_datadir}/skj-logos/skj-wordmark-lightbg.svg

for s in 16 22 24 32 36 48 64 96 128 256 512; do
  install -Dpm 0644 $A/icons/$s/skj-logo-icon.png %{buildroot}%{_datadir}/icons/hicolor/${s}x${s}/apps/skj-logo-icon.png
done
for s in 16 22 24 32 36 48 96 256; do
  install -Dpm 0644 $A/icons/$s/skj-logo-icon.png %{buildroot}%{_datadir}/icons/hicolor/${s}x${s}/apps/fedora-logo-icon.png
  install -Dpm 0644 $A/icons/$s/skj-logo-icon.png %{buildroot}%{_datadir}/icons/hicolor/${s}x${s}/places/start-here.png
done
install -Dpm 0644 $A/svg/skj-logo-mark.svg %{buildroot}%{_datadir}/icons/hicolor/scalable/apps/skj-logo-icon.svg
install -Dpm 0644 $A/svg/skj-logo-mark.svg %{buildroot}%{_datadir}/icons/hicolor/scalable/apps/start-here.svg
install -Dpm 0644 $A/svg/skj-logo-mark.svg %{buildroot}%{_datadir}/icons/hicolor/scalable/places/start-here.svg
install -Dpm 0644 $A/svg/skj-logo-mark-symbolic.svg %{buildroot}%{_datadir}/icons/hicolor/symbolic/apps/skj-logo-icon-symbolic.svg

install -Dpm 0644 $A/favicon.png            %{buildroot}%{_sysconfdir}/favicon.png
install -Dpm 0644 $A/logo.png               %{buildroot}%{_datadir}/pixmaps/fedora-logo.png
install -Dpm 0644 $A/logo-small.png         %{buildroot}%{_datadir}/pixmaps/fedora-logo-small.png
install -Dpm 0644 $A/logo-med.png           %{buildroot}%{_datadir}/pixmaps/fedora_logo_med.png
install -Dpm 0644 $A/whitelogo-med.png      %{buildroot}%{_datadir}/pixmaps/fedora_whitelogo_med.png
install -Dpm 0644 $A/svg/skj-wordmark-darkbg.svg %{buildroot}%{_datadir}/pixmaps/fedora_whitelogo.svg
install -Dpm 0644 $A/gdm-logo.png           %{buildroot}%{_datadir}/pixmaps/fedora-gdm-logo.png
install -Dpm 0644 $A/logo-sprite.png        %{buildroot}%{_datadir}/pixmaps/fedora-logo-sprite.png
install -Dpm 0644 $A/svg/skj-logo-mark.svg  %{buildroot}%{_datadir}/pixmaps/fedora-logo-sprite.svg
install -Dpm 0644 $A/system-logo-white.png  %{buildroot}%{_datadir}/pixmaps/system-logo-white.png
install -Dpm 0644 $A/bootlogo_128.png       %{buildroot}%{_datadir}/pixmaps/bootloader/bootlogo_128.png
install -Dpm 0644 $A/bootlogo_256.png       %{buildroot}%{_datadir}/pixmaps/bootloader/bootlogo_256.png

# Anaconda installer
install -Dpm 0644 $A/anaconda-sidebar-logo.png %{buildroot}%{_datadir}/anaconda/pixmaps/sidebar-logo.png
install -Dpm 0644 $A/anaconda-sidebar-bg.png   %{buildroot}%{_datadir}/anaconda/pixmaps/sidebar-bg.png
install -Dpm 0644 $A/anaconda-topbar-bg.png    %{buildroot}%{_datadir}/anaconda/pixmaps/topbar-bg.png
install -Dpm 0644 $A/anaconda-header.png       %{buildroot}%{_datadir}/anaconda/pixmaps/anaconda_header.png
# the inherited Fedora Anaconda profile loads its stylesheet from this path
install -Dpm 0644 $S/skj.css                   %{buildroot}%{_datadir}/anaconda/pixmaps/fedora.css
install -Dpm 0644 $A/icons/256/skj-logo-icon.png %{buildroot}%{_datadir}/icons/hicolor/256x256/apps/anaconda.png
# "Install to Hard Drive" (liveinst.desktop) uses this icon name; on Fedora it
# comes from fedora-logos and breeze-icon-theme-fedora, which we don't ship.
for s in 16 22 24 32 48 64 96 128 256 512; do
  install -Dpm 0644 $A/icons/$s/skj-logo-icon.png %{buildroot}%{_datadir}/icons/hicolor/${s}x${s}/apps/org.fedoraproject.AnacondaInstaller.png
done
install -Dpm 0644 $A/svg/skj-logo-mark.svg %{buildroot}%{_datadir}/icons/hicolor/scalable/apps/org.fedoraproject.AnacondaInstaller.svg
install -Dpm 0644 $A/svg/skj-logo-mark-symbolic.svg %{buildroot}%{_datadir}/icons/hicolor/symbolic/apps/org.fedoraproject.AnacondaInstaller-symbolic.svg

# Anaconda web UI (Cockpit) branding: cockpit-ws looks up branding/<ID> first
C=%{buildroot}%{_datadir}/cockpit/branding/skj-os-ez
install -Dpm 0644 $S/cockpit-branding.css $C/branding.css
ln -s ../../../pixmaps/system-logo-white.png $C/logo.png
ln -s ../../../pixmaps/fedora-logo-sprite.png $C/apple-touch-icon.png
ln -s ../../../../../etc/favicon.png $C/favicon.ico

# Watermark used by the stock spinner/bgrt Plymouth themes
install -Dpm 0644 $A/plymouth-watermark.png %{buildroot}%{_datadir}/plymouth/themes/spinner/watermark.png

# --- skj-backgrounds-kde ----------------------------------------------------
W=%{buildroot}%{_datadir}/wallpapers/SKJ
install -Dpm 0644 $S/wallpaper-metadata.json     $W/metadata.json
install -Dpm 0644 $A/wallpaper/3840x2160.png     $W/contents/images/3840x2160.png
install -Dpm 0644 $A/wallpaper/1920x1080.png     $W/contents/images/1920x1080.png
install -Dpm 0644 $A/wallpaper/1080x1920.png     $W/contents/images/1080x1920.png
install -Dpm 0644 $A/wallpaper/screenshot.png    $W/contents/screenshot.png
# Fedora's KDE defaults point at wallpapers/Fedora -> Default
ln -s SKJ %{buildroot}%{_datadir}/wallpapers/Default
install -Dpm 0644 $A/wallpaper/3840x2160.png     %{buildroot}%{_datadir}/backgrounds/skj/skj-default.png
# Login screen (SDDM) background
install -d %{buildroot}%{_datadir}/sddm/themes/01-breeze-fedora
cat > %{buildroot}%{_datadir}/sddm/themes/01-breeze-fedora/theme.conf.user <<EOF
[General]
background=%{_datadir}/wallpapers/SKJ/contents/images/3840x2160.png
type=image
EOF

# --- plymouth-theme-skj -----------------------------------------------------
P=%{buildroot}%{_datadir}/plymouth/themes/skj
install -Dpm 0644 $S/skj.plymouth           $P/skj.plymouth
install -Dpm 0644 $A/plymouth-watermark.png $P/watermark.png
# reuse the spinner theme's animation and password dialog images
for f in bullet capslock entry keyboard keymap-render lock; do
  ln -s ../spinner/$f.png $P/$f.png
done
for i in $(seq -w 1 30); do ln -s ../spinner/throbber-00$i.png $P/throbber-00$i.png; done
for i in $(seq -w 1 36); do ln -s ../spinner/animation-00$i.png $P/animation-00$i.png; done

# --- skj-fastfetch-config ---------------------------------------------------
install -Dpm 0644 $S/fastfetch-config.jsonc %{buildroot}%{_sysconfdir}/xdg/fastfetch/config.jsonc
install -Dpm 0644 $S/fastfetch-logo.txt     %{buildroot}%{_datadir}/skj/fastfetch/logo.txt

%post -n plymouth-theme-skj
# Make SKJ the default splash unless the admin picked something else.
current=$(plymouth-set-default-theme 2>/dev/null || :)
if [ -z "$current" ] || [ "$current" = "bgrt" ] || [ "$current" = "spinner" ] || [ "$current" = "text" ]; then
  plymouth-set-default-theme skj >/dev/null 2>&1 || :
fi

%files
%{_datadir}/skj-logos/
%{_datadir}/icons/hicolor/*/apps/skj-logo-icon.png
%{_datadir}/icons/hicolor/*/apps/fedora-logo-icon.png
%{_datadir}/icons/hicolor/*/places/start-here.png
%{_datadir}/icons/hicolor/256x256/apps/anaconda.png
%{_datadir}/icons/hicolor/*/apps/org.fedoraproject.AnacondaInstaller.png
%{_datadir}/icons/hicolor/scalable/apps/org.fedoraproject.AnacondaInstaller.svg
%{_datadir}/icons/hicolor/symbolic/apps/org.fedoraproject.AnacondaInstaller-symbolic.svg
%{_datadir}/icons/hicolor/scalable/apps/skj-logo-icon.svg
%{_datadir}/icons/hicolor/scalable/apps/start-here.svg
%{_datadir}/icons/hicolor/scalable/places/start-here.svg
%{_datadir}/icons/hicolor/symbolic/apps/skj-logo-icon-symbolic.svg
%config(noreplace) %{_sysconfdir}/favicon.png
%{_datadir}/pixmaps/fedora-logo.png
%{_datadir}/pixmaps/fedora-logo-small.png
%{_datadir}/pixmaps/fedora_logo_med.png
%{_datadir}/pixmaps/fedora_whitelogo_med.png
%{_datadir}/pixmaps/fedora_whitelogo.svg
%{_datadir}/pixmaps/fedora-gdm-logo.png
%{_datadir}/pixmaps/fedora-logo-sprite.png
%{_datadir}/pixmaps/fedora-logo-sprite.svg
%{_datadir}/pixmaps/system-logo-white.png
%{_datadir}/pixmaps/bootloader/
%{_datadir}/anaconda/pixmaps/sidebar-logo.png
%{_datadir}/anaconda/pixmaps/sidebar-bg.png
%{_datadir}/anaconda/pixmaps/topbar-bg.png
%{_datadir}/anaconda/pixmaps/anaconda_header.png
%{_datadir}/anaconda/pixmaps/fedora.css
%dir %{_datadir}/cockpit
%dir %{_datadir}/cockpit/branding
%{_datadir}/cockpit/branding/skj-os-ez/
%dir %{_datadir}/plymouth/themes/spinner
%{_datadir}/plymouth/themes/spinner/watermark.png

%files -n skj-backgrounds-kde
%{_datadir}/wallpapers/SKJ/
%{_datadir}/wallpapers/Default
%{_datadir}/backgrounds/skj/
%{_datadir}/sddm/themes/01-breeze-fedora/theme.conf.user

%files -n plymouth-theme-skj
%{_datadir}/plymouth/themes/skj/

%files -n skj-fastfetch-config
%config(noreplace) %{_sysconfdir}/xdg/fastfetch/config.jsonc
%{_datadir}/skj/fastfetch/

%changelog
* Fri Oct 02 2026 SKJ OS <jnowakowski741@gmail.com> - 44.0-3
- Cockpit branding for skj-os-ez: the Anaconda web UI installer header
  uses the SKJ palette instead of Fedora blue

* Fri Oct 02 2026 SKJ OS <jnowakowski741@gmail.com> - 44.0-2
- Ship the org.fedoraproject.AnacondaInstaller icon (SKJ logo) so
  "Install to Hard Drive" no longer shows a blank icon

* Tue Sep 29 2026 SKJ OS <jnowakowski741@gmail.com> - 44.0-1
- First SKJ OS EZ logos, wallpaper, boot splash and fastfetch logo
