# Anaconda configuration file for SKJ OS EZ ISO Edition (KDE Plasma).
# Inherits everything from Fedora KDE Plasma Desktop Edition, which it is based on.

[Profile]
profile_id = skj-os-ez-kde
base_profile = fedora-kde

[Profile Detection]
# Match os-release values.
os_id = skj-os-ez
variant_id = kde
